# Generated by Django 4.1.4 on 2023-01-26 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livros',
            name='liv_leitura',
            field=models.BooleanField(default=False),
        ),
    ]
